name: p1_app
description: A new Flutter project.

publish_to: "none" # Prevents publishing to pub.dev (optional)

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^9.6.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
